// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IpDisabled: typeof import('./components/confirm/IpDisabled.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    LayoutLeftMenu: typeof import('./components/LayoutLeftMenu.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    PageTemplate: typeof import('./components/PageTemplate/PageTemplate.vue')['default']
    SystemInformation: typeof import('./components/LandingPage/SystemInformation.vue')['default']
    TitleBar: typeof import('./components/common/TitleBar.vue')['default']
    UpdataProgress: typeof import('./components/updataProgress/index.vue')['default']
    UserMenu: typeof import('./components/userMenu.vue')['default']
  }
}

export { }
